; This file was automatically generated by ScriptHubImporter.py
<<<<<<< HEAD
global g_ImportsGameVersion64 := 627
global g_ImportsGameVersionPostFix64 := ""
=======
global g_ImportsGameVersion64 := 632
global g_ImportsGameVersionPostFix64 := ""
global g_ImportsGameVersionPlatform64 := "Steam"
>>>>>>> 2c5be581a36002d1a8181937ba293b014543facc
